name: 'Code sign a file with pfx certificate'
description: 'Sign a file with a pfx certificate.'
branding:
  icon: 'award'
  color: 'green'
inputs:
  cert_body:
    description: 'The base64 encoded certificate'
    required: true
  folder:
    description: 'The folder that contains the files to sign'
    required: true
  recursive:
    description: 'Recursively search for supported files'
    required: false
  cert_pswd:
    description: 'The password'
    required: false
  cert_algo:
    description: 'Algorithm used to generate the certificate'
    required: false
  cert_hash:
    description: 'The hash of the certificate'
    required: false
  cert_name:
    description: 'The name of the certificate'
    required: false
  timestamp_url:
    description: 'URL of the timestamp server'
    required: false
  debug:
    description: 'Insert the debug option'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
